alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias decrypt='openssl enc -d -aes-256-cbc -a'
alias e='emacs -nw'
alias egrep='egrep --color=auto'
alias encrypt='openssl enc -aes-256-cbc -a -salt'
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gaa='git add -A $(git rev-parse --show-toplevel 2>/dev/null)'
alias gai='git add -i'
alias gap='git add -p'
alias gax='git log --pretty=oneline -S'
alias gb='git branch'
alias gbD='git branch -D'
alias gba='git branch -a'
alias gca='git commit --amend'
alias gch='git checkout'
alias gco='git commit'
alias gcoa='git commit --amend'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='gaa && git cherry-pick --continue'
alias git='git --no-pager'
alias gl='git --no-pager log --pretty=oneline -20'
alias gm='git merge'
alias gma='git merge --abort'
alias gn='git checkout -b'
alias gr='git remove'
alias gra='git remote add'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='gaa && git rebase --continue'
alias grbi='git rebase -i'
alias grbi1='git rebase -i HEAD~1'
alias grbi10='git rebase -i HEAD~10'
alias grbi100='git rebase -i HEAD~100'
alias grbi2='git rebase -i HEAD~2'
alias grbi20='git rebase -i HEAD~20'
alias grbi3='git rebase -i HEAD~3'
alias grbi4='git rebase -i HEAD~4'
alias grbi5='git rebase -i HEAD~5'
alias grbs='git rebase --skip'
alias grep='grep --color=auto'
alias grh='git reset --hard'
alias grh0='git reset --hard HEAD'
alias grh1='git reset --hard HEAD~1'
alias grh100='git reset --hard HEAD~100'
alias grh2='git reset --hard HEAD~2'
alias grh3='git reset --hard HEAD~3'
alias grh4='git reset --hard HEAD~4'
alias grh5='git reset --hard HEAD~5'
alias grm='git reset --mixed'
alias grm0='git reset --mixed HEAD'
alias grm1='git reset --mixed HEAD~1'
alias grm2='git reset --mixed HEAD~2'
alias grm3='git reset --mixed HEAD~3'
alias grm4='git reset --mixed HEAD~4'
alias grm5='git reset --mixed HEAD~5'
alias gru='git remote update'
alias grv='git remote -v'
alias gs='git status'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alFX'
alias ls='ls --color --group-directories-first'
alias mkdirp='mkdir -p'
alias ocaml='rlwrap -H /home/bibou/.ocaml_history -D 2 -i -s 10000 ocaml'
alias projects='cd ~/Projects'

alias test-morphextensions='cd ~/Projects/MorphExtensions;mvn package;./src/test/resources/javamc ./src/test/resources/Hello.java'
alias jdk9='cd /home/bibou/Projects/openjdk-repos/jdk9'
alias jmh-now='mvn archetype:generate -DinteractiveMode=false -DarchetypeGroupId=org.openjdk.jmh -DarchetypeArtifactId=jmh-java-benchmark-archetype -DgroupId=org.sample -DartifactId=test -Dversion=1.0'
